# Generated by Django 5.0.14 on 2025-11-11 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("apto", "Apto Físico General"),
                            ("registro", "Registro Médico"),
                            ("cus", "Certificado Único de Salud"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("destinatario", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=255)),
                ("cuerpo", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="PENDIENTE", max_length=20)),
                ("respuesta_servidor", models.TextField(blank=True, null=True)),
                (
                    "fecha_envio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Registro de Email",
                "verbose_name_plural": "Registros de Emails",
                "db_table": "email_log",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
