# Generated by Django 5.0.14 on 2025-08-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RegistroMedico", "0002_registromedico_competencia_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='registromedico',
                    table='registromedico_registromedico',
                ),
            ],
            database_operations=[],
        ),
    ]
