# Generated by Django 5.0.14 on 2025-08-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "RegistroMedico",
            "0004_remove_registromedico_rm_torneo_xor_competencia_and_more",
        ),
        ("RegistroMedico", "0005_align_to_ficha_registro"),
    ]

    operations = []
