# Generated by Django 5.0.14 on 2025-08-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medico", "0004_medico_direccion"),
        ("RegistroMedico", "0006_merge_20250813_2021"),
        ("persona", "0003_actividadgeneral_jugadoractividadgeneral"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registromedico",
            name="rm_torneo_xor_competencia",
        ),
        migrations.AlterField(
            model_name="eliminacionfichamedica",
            name="medico",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="registromedico",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("competencia__isnull", True), ("torneo__isnull", False)),
                    models.Q(("competencia__isnull", False), ("torneo__isnull", True)),
                    _connector="OR",
                ),
                name="rm_torneo_xor_competencia",
            ),
        ),
    ]
