
"""
Django settings for FichaMedica project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!cy-2z7&5o=i(#euh@gvqr_o)!@-twm_&=6!o-487&79dybjsq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
ALLOWED_HOSTS = ['www.checkeate.com.ar', 'checkeate.com.ar', '127.0.0.1', 'localhost']

# Tiempo máximo de inactividad (en segundos) antes de que la sesión expire
SESSION_COOKIE_AGE = 900  # 15 minutos
# Tiempo máximo de inactividad antes de que la sesión se cierre automáticamente (en segundos)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Esto hace que la sesión se cierre al cerrar el navegador
SESSION_SAVE_EVERY_REQUEST = False  # No renueva la expiración de la sesión en cada solicitud

# Application definition

INSTALLED_APPS = [
    'account.apps.AccountConfig',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.sitemaps',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'widget_tweaks',
    'publicidad',
    'persona',
    'Medico',
    'InfoNovedades',
    'estudiante',
    'Cus',
    'aptos_generales',
    'aptos_externos',
    'ApiRest',


    'Representate',

    'RegistroMedico',



]
# Configuración de sitio
SITE_ID = 1


# Configuracion del servidor para el email
# settings.py

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'c2621570.ferozo.com'
    EMAIL_PORT = 465
    EMAIL_USE_SSL = True  # ✅ correcto para Ferozo
    EMAIL_USE_TLS = False  # ⚠️ debe ser False
    DEFAULT_FROM_EMAIL = 'info@checkeate.com.ar'

    # ✅ Múltiples cuentas de correo
    EMAIL_ACCOUNTS = {
        'soporte': {
            'EMAIL_HOST_USER': 'soporte@checkeate.com.ar',
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_PASSWORD_SOPORTE')
        },
        'notificaciones': {
            'EMAIL_HOST_USER': 'notificaciones@checkeate.com.ar',
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_PASSWORD_NOTIFICACIONES')
        },
        'atencion': {
            'EMAIL_HOST_USER': 'atencion@checkeate.com.ar',
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_PASSWORD_ATENCION')
        },
        'info': {
            'EMAIL_HOST_USER': 'info@checkeate.com.ar',
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_PASSWORD_INFO')
        },
        'admin': {
            'EMAIL_HOST_USER': 'admin@checkeate.com.ar',
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_PASSWORD_ADMIN')
        },
    }

SECRET_CRON_TOKEN = 'clave-123456'

AUTHENTICATION_BACKENDS = [
    'account.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'FichaMedica.middleware.disable_cache.DisableCacheMiddleware',
]

ROOT_URLCONF = 'FichaMedica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FichaMedica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'proyecto_salud',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}
 """

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'checkeate_db',
        'USER': 'super',
        'PASSWORD': 'asantoni_888',
        'HOST': 'Salud-4592.postgres.pythonanywhere-services.com',
        'PORT': '14592',
    }
}

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'checkeate_db',
        'USER': 'postgres',
        'PASSWORD': 'ale123',
        'HOST': 'localhost',
        'PORT': '5433',
    }
} """

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGOUT_REDIRECT_URL = 'home'  # URL a la que redirige después de hacer logout
LOGIN_URL = '/account/login/'  # Página de login si no está autenticado

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'ApiRest.exceptions.custom_exception_handler',
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}

CORS_ALLOW_ALL_ORIGINS = True
# esto lo agregue para poder trabajar en local 
try:
    from .settings_local import *
except ImportError:
    pass
