# Generated by Django 5.0.14 on 2025-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medico", "0003_documentos_contrato_aceptado"),
    ]

    operations = [
        migrations.AddField(
            model_name="medico",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
