# Generated by Django 5.0.14 on 2025-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medico", "0004_medico_direccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
