# Generated by Django 5.0.14 on 2026-01-27 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Medico", "0005_alter_medico_matricula"),
        ("account", "0006_alter_profile_rol"),
        ("aptos_generales", "0003_alter_antecedenteaptogeneral_vacunacion"),
        ("persona", "0005_alter_persona_profile_alter_persona_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComentarioAptoGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol_autor",
                    models.CharField(
                        choices=[
                            ("MEDICO", "Médico"),
                            ("REPRESENTANTE", "Representante"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comentario", models.TextField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "apto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
                (
                    "autor_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservacionPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol_autor",
                    models.CharField(
                        choices=[
                            ("MEDICO", "Médico"),
                            ("REPRESENTANTE", "Representante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField()),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "autor_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.profile",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones",
                        to="persona.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
