# Generated by Django 5.0.14 on 2026-01-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Medico", "0006_comentarioaptogeneral_observacionpersona"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComentarioAptoGeneral",
        ),
    ]
