# Generated by Django 5.0.14 on 2025-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("jugador", "Jugador"),
                    ("medico", "Médico"),
                    ("representante", "Representante"),
                    ("colegio", "Colegio"),
                    ("estudiante", "Estudiante"),
                    ("paciente", "Paciente"),
                    ("actividad", "Actividad"),
                ],
                default="jugador",
                max_length=20,
            ),
        ),
    ]
