# Generated by Django 5.0.14 on 2026-01-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0006_alter_profile_rol"),
        ("persona", "0005_alter_persona_profile_alter_persona_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AptoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo_pdf", models.FileField(upload_to="aptos_externos/")),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones administrativas del apto externo",
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actividad general asociada al apto externo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aptos_externos",
                        to="persona.actividadgeneral",
                    ),
                ),
                (
                    "competencia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Competencia específica dentro del torneo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aptos_externos",
                        to="persona.competencia",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aptos_externos",
                        to="persona.persona",
                    ),
                ),
                (
                    "representante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aptos_externos_cargados",
                        to="account.profile",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Torneo asociado al apto externo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aptos_externos",
                        to="persona.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apto Externo",
                "verbose_name_plural": "Aptos Externos",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
