# Generated by Django 5.0.14 on 2025-09-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Representate", "0002_representecolegio"),
        ("account", "0006_alter_profile_rol"),
        ("persona", "0003_actividadgeneral_jugadoractividadgeneral"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepresentanteActividadGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representantes_actividad",
                        to="persona.actividadgeneral",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
            ],
        ),
    ]
