# Generated by Django 5.0.14 on 2025-08-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Medico", "0004_medico_direccion"),
        ("persona", "0003_actividadgeneral_jugadoractividadgeneral"),
    ]

    operations = [
        migrations.CreateModel(
            name="AptoGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESO", "En proceso"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PROCESO",
                        max_length=45,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_caducidad", models.DateField(blank=True, null=True)),
                ("fecha_de_llenado", models.DateField(blank=True, null=True)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("consentimiento_persona", models.BooleanField(blank=True, null=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aptos",
                        to="persona.actividadgeneral",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aptos_generales",
                        to="persona.jugador",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Medico.medico",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="AntecedenteAptoGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fue_operado",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "toma_medicacion",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "estuvo_internado",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "sufre_hormigueos",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "es_diabetico",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "es_asmatico",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "es_alergico",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "alerg_observ",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "antecedente_epilepsia",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "desviacion_columna",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "dolor_cintura",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("fracturas", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "dolores_articulares",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "falta_aire",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "traumatismos_craneo",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "dolor_pecho",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "perdida_conocimiento",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "presion_arterial",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "muerte_subita_familiar",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "enfermedad_cardiaca_familiar",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "soplo_cardiaco",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "abstenerse_competencia",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "antecedentes_coronarios_familiares",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fumar_hipertension_diabetes",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fhd_observacion",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "consumo_cocaina_anabolicos",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "cca_observaciones",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "vacunacion",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Esquema de vacunación completo",
                        null=True,
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedentes_por_apto",
                        to="persona.jugador",
                    ),
                ),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedentes_snapshot",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ExamenAbdomenGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_abdomen",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="ExamenCardiovascularGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auscultacion", models.TextField(blank=True, null=True)),
                (
                    "ta1",
                    models.CharField(
                        blank=True,
                        help_text="Tensión arterial 1",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ta2",
                    models.CharField(
                        blank=True,
                        help_text="Tensión arterial 2",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("pulso", models.CharField(blank=True, max_length=50, null=True)),
                ("ecg", models.FileField(blank=True, null=True, upload_to="ecg/")),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_cardiovascular",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="ExamenFisicoGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "perimetro_cintura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "diagnostico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EUTROFICO", "Eutrófico"),
                            ("ENDOMORFO", "Endomorfo"),
                            ("MESOMORFO", "Mesomorfo"),
                            ("ECTOMORFO", "Ectomorfo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_fisico",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="ExamenGenitourinarioGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_genitourinario",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="ExamenRespiratorioGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "murmullo_vesicular",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ruidos_agregados",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "saturacion_o2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_respiratorio",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="ExamenSomaGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_soma",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.CreateModel(
            name="MotivoActividadGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competitivo", models.BooleanField(default=False)),
                ("recreativo", models.BooleanField(default=False)),
                ("por_salud", models.BooleanField(default=False)),
                (
                    "salud_detalle",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("por_lesion", models.BooleanField(default=False)),
                (
                    "lesion_detalle",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "apto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motivo_actividad",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "ordering": ["apto"],
            },
        ),
        migrations.AddConstraint(
            model_name="antecedenteaptogeneral",
            constraint=models.UniqueConstraint(
                fields=("apto",), name="uniq_antecedente_por_apto"
            ),
        ),
    ]
