# Generated by Django 5.0.14 on 2025-08-26 20:58

import aptos_generales.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aptos_generales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudiosAptoGeneral",
            fields=[
                ("idestudio", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_estudio",
                    models.CharField(
                        choices=[
                            ("ORINA", "Análisis de Orina"),
                            ("ELECTRO", "Electrocardiograma"),
                            ("ERGOMETRIA", "Ergometría"),
                            ("LABORATORIO", "Laboratorio"),
                            ("IMAGEN", "Estudio por Imágenes"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="estudios_apto/"),
                ),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "fecha_caducidad",
                    models.DateField(
                        default=aptos_generales.models.default_fecha_caducidad
                    ),
                ),
                (
                    "apto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios_apto",
                        to="aptos_generales.aptogeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio Apto General",
                "verbose_name_plural": "Estudios Aptos Generales",
                "db_table": "estudios_apto_generales",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
