# Generated by Django 5.0.14 on 2026-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aptos_generales", "0002_estudiosaptogeneral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antecedenteaptogeneral",
            name="vacunacion",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
